/// Model representing a service request generated by the AI agent
class ServiceRequest {
  final String category;
  final String description;
  final Map<String, dynamic> details;
  final List<String> mediaUrls;
  final String? location;
  final String? contactInfo;
  final Map<String, dynamic>? pricing;
  final Map<String, dynamic>? availability;
  final List<String> tags;
  final String? priority;
  final DateTime createdAt;
  final String? userId;
  final String? requestId;
  
  ServiceRequest({
    required this.category,
    required this.description,
    required this.details,
    required this.mediaUrls,
    this.location,
    this.contactInfo,
    this.pricing,
    this.availability,
    List<String>? tags,
    this.priority,
    DateTime? createdAt,
    this.userId,
    this.requestId,
  }) : tags = tags ?? [],
       createdAt = createdAt ?? DateTime.now();
  
  /// Convert to JSON for storage/transmission
  Map<String, dynamic> toJson() {
    return {
      'category': category,
      'description': description,
      'details': details,
      'mediaUrls': mediaUrls,
      'location': location,
      'contactInfo': contactInfo,
      'pricing': pricing,
      'availability': availability,
      'tags': tags,
      'priority': priority,
      'createdAt': createdAt.toIso8601String(),
      'userId': userId,
      'requestId': requestId,
    };
  }
  
  /// Create from JSON
  factory ServiceRequest.fromJson(Map<String, dynamic> json) {
    return ServiceRequest(
      category: json['category'] ?? '',
      description: json['description'] ?? '',
      details: Map<String, dynamic>.from(json['details'] ?? {}),
      mediaUrls: List<String>.from(json['mediaUrls'] ?? []),
      location: json['location'],
      contactInfo: json['contactInfo'],
      pricing: json['pricing'] != null ? Map<String, dynamic>.from(json['pricing']) : null,
      availability: json['availability'] != null ? Map<String, dynamic>.from(json['availability']) : null,
      tags: List<String>.from(json['tags'] ?? []),
      priority: json['priority'],
      createdAt: json['createdAt'] != null ? DateTime.parse(json['createdAt']) : DateTime.now(),
      userId: json['userId'],
      requestId: json['requestId'],
    );
  }
  
  /// Create a copy with updated fields
  ServiceRequest copyWith({
    String? category,
    String? description,
    Map<String, dynamic>? details,
    List<String>? mediaUrls,
    String? location,
    String? contactInfo,
    Map<String, dynamic>? pricing,
    Map<String, dynamic>? availability,
    List<String>? tags,
    String? priority,
    DateTime? createdAt,
    String? userId,
    String? requestId,
  }) {
    return ServiceRequest(
      category: category ?? this.category,
      description: description ?? this.description,
      details: details ?? this.details,
      mediaUrls: mediaUrls ?? this.mediaUrls,
      location: location ?? this.location,
      contactInfo: contactInfo ?? this.contactInfo,
      pricing: pricing ?? this.pricing,
      availability: availability ?? this.availability,
      tags: tags ?? this.tags,
      priority: priority ?? this.priority,
      createdAt: createdAt ?? this.createdAt,
      userId: userId ?? this.userId,
      requestId: requestId ?? this.requestId,
    );
  }
  
  @override
  String toString() {
    return 'ServiceRequest(category: $category, description: $description, location: $location, priority: $priority)';
  }
} 